version: '3.8'

services:
  rcp-app:
    build: .
    ports:
      - "${PORT:-6500}:80"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=80
      - ADMIN_USER=${ADMIN_USER:-Federacion}
      - ADMIN_PASS=${ADMIN_PASS:-Faf12345*}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@rcp-cursos.com}
    restart: unless-stopped